services:
  # localhost:8080
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    env_file: stack.env
    volumes:
      - $HOME/.config/sabnzbd:/config
      - $HOME/downloads/sabnzbd:/data/sabnzbd
    ports:
      - 8080:8080
    restart: unless-stopped

  # localhost:7878
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file: stack.env
    volumes:
      - $HOME/.config/radarr:/config
      - $HOME/downloads/sabnzbd:/data/sabnzbd
      - /mnt/media/data/media:/data/media
    ports:
      - 7878:7878
    restart: unless-stopped

  # localhost:8989
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file: stack.env
    volumes:
      - $HOME/.config/sonarr:/config
      - $HOME/downloads/sabnzbd:/data/sabnzbd
      - /mnt/media/data/media:/data/media
    ports:
      - 8989:8989
    restart: unless-stopped

  # localhost:6767
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    env_file: stack.env
    volumes:
      - $HOME/.config/bazarr:/config
      - /mnt/media/data/media:/data/media
    ports:
      - 6767:6767
    restart: unless-stopped
